# Generated by Django 5.0.1 on 2025-03-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_logos/'),
        ),
    ]
